kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: es-storage
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: zeroedthick
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-claim-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: es-storage
